### PR TITLE
Feature/project setup

### PR DESCRIPTION
**Pull request by lovisgod**
## Description
The backend app for the project was set up.
Nodejs express framework was used,
PostgreSQL was used for database,
Sequelize was used as ORM 
Mocha was used to setup Test Suite.

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #23  

## How Has This Been Tested?
1. Clone/Pull/Fetch this branch.
2. Run `npm install` to install the dependencies.
3. Run `npm test` to run the tests.
4. Test the `/api/v1` endpoint of the server with postman

## Screenshots (if applicable, else remove this line / section)

None

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by adaezeodurukwe — COMMENTED** [review]
kindly remove all commented code

**Comment by lovisgod** [comment]
> kindly remove all commented code

commented codes have been removed

**Comment by John-Akins** [comment]
Looks good

**Comment by John-Akins** [comment]
Looks good. Great Job man, we're good to go.

**Review by John-Akins — APPROVED** [review]
Awesome, looks like we're good to go

**Review by adaezeodurukwe — APPROVED** [review]

**Pull request merged**
